# Shree KRISHNAya Namaha
# Exports bib file
# Author: Nagabhushan S N
# Last Modified: 25-04-2020
import datetime
import json
from pathlib import Path

from src.data_structures.EntryCollection import EntryCollection


def export_bib(configs_filepath: Path):
    with open(configs_filepath.as_posix(), 'r') as configs_file:
        configs = json.load(configs_file)

    entries = EntryCollection().entries
    export_strings = []
    date_today = datetime.datetime.now().strftime('%d/%m/%Y %I:%M:%S %p')
    export_strings.append(f'% Generated by Bibtex Manager on {date_today}\n% Configs: {configs_filepath.name}')
    for entry in entries:
        fields_names = configs[entry.__class__.__name__]
        export_string = entry.get_export_string(fields_names)
        export_strings.append(export_string)
    final_string = '\n\n'.join(export_strings)

    output_dirpath = Path('../out')
    output_dirpath.mkdir(parents=True, exist_ok=True)
    output_filepath = output_dirpath / f'references_{configs_filepath.stem}.bib'
    with open(output_filepath.as_posix(), 'w') as output_file:
        output_file.write(final_string)
    return


def demo1():
    configs_filepath = Path('../res/configs/journal.json')
    export_bib(configs_filepath)
    return


def demo2():
    configs_dirpath = Path('../res/configs')
    for configs_filepath in configs_dirpath.rglob('*.json'):
        export_bib(configs_filepath)


def main():
    demo2()
    return


if __name__ == '__main__':
    main()
